# Generated by Django 4.2.1 on 2023-05-25 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="public",
        ),
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
    ]
